### ISSUE TITLE
The error of estimator.py 

### ISSUE THREAD

**Issue by gouyinchao** [YangZeyu95/unofficial-implement-of-openpose#11]
Hi,
When I run the estimator.py ,I will get the error as follow :File Not Found Error: [Errno 2] No such file or directory: './etcs/heatpaf1.pkl',How can I get the file of 'heatpaf1.pkl' ?Can you please help?

**Comment by YangZeyu95** [comment]
'estimator.py' is used to estimate pose from keypoints and paf, you can just run it for test the capability of the estimator with 'heatpaf1.pkl'. So you will need to provide heatpaf1.pkl by yourself or run 'test.py' in which network has already provided keypoints and paf. And the code of 'estimator.py' is from  https://github.com/ildoonet/tf-pose-estimation but I can't find the 'heatpaf1.pkl' in this repo. So you can ask the author of the 'estimator.py' for 'heatpaf1.pkl' or make it yourself or just run 'test.py' which call estimator as a part. btw, I'm curious about why you want to run 'estimator.py'.

**Comment by gouyinchao** [comment]
Thanks for your time.I run 'estimator.py' due to my mistake , now i get it.But i encounter anoher error.When i run the 'run.py',i get the vedio of "our.mp4",but i cann't open it.The errors showed as follows:
2019󈚥󈚼 02:06:03.929841: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019󈚥󈚼 02:06:05.337922: W tensorflow/core/framework/allocator.cc:122] Allocation of 411041792 exceeds 10% of system memory.
2019󈚥󈚼 02:06:12.119310: W tensorflow/core/framework/allocator.cc:122] Allocation of 411041792 exceeds 10% of system memory.
2019󈚥󈚼 02:06:21.022819: W tensorflow/core/framework/allocator.cc:122] Allocation of 411041792 exceeds 10% of system memory. 
what's matter with me ?Can you please help?

**Comment by YangZeyu95** [comment]
It looks like your memory is not enough. Which GPU do you use?

**Comment by gouyinchao** [comment]
It seems that GPU of my computer is not powerful enough,thank you for your reply.
