### ISSUE TITLE
找不到slidingwindow.py

### ISSUE THREAD

**Issue by bitgs** [YangZeyu95/unofficial-implement-of-openpose#14]
zeyu你好，
我在执行run.py的时候报错如下：
File "C:\Users\Yuan\Downloads\unofficial-implement-of-openpose-master\estimator.py", line 4, in <module>
    import slidingwindow as sw
ModuleNotFoundError: No module named 'slidingwindow'

找不到slidingwindow.py。请帮忙看一下，谢谢！

**Comment by mc261670164** [comment]
当我在运行run.py的时候，提示ModuleNotFoundError: No module named 'slidingwindow'，这个错误你解决了吗？

**Comment by mc261670164** [comment]
just 'pip install slidingwindow'
