### ISSUE TITLE
分析视频的时候只有0.12帧，请问是电脑的问题吗？

### ISSUE THREAD

**Issue by colall9414** [YangZeyu95/unofficial-implement-of-openpose#18]
您好，我在测试分析视频和用摄像头的时候处理速度只有每秒0.12帧，请问是电脑的问题吗？

**Comment by YangZeyu95** [comment]
能列下配置吗，如果输入图像尺寸比价大的话也会影响速度

**Comment by colall9414** [comment]
显卡: Intel Iris Graphics 550 1536 Mo
处理器: 2,9 GHz Intel Core i5
内存: 16 Go 2133 MHz LPDDR3
我有试过把视频压缩过，但是好像没有变化

**Comment by YangZeyu95** [comment]
显卡不行，你这只能跑cpu，得用N卡

**Comment by colall9414** [comment]
原来是这样，谢谢大佬^^
