### ISSUE TITLE
导入已训练模型后test出错

### ISSUE THREAD

**Issue by jiahui-wei-perso** [YangZeyu95/unofficial-implement-of-openpose#28]
你好，我导入了你提供的模型，然后在做test的时候发现
 File "run.py", line 160, in <module>
    peaks, heatmap, vectormap = sess.run([tensor_peaks, hm_up, cpm_up], feed_dict={raw_img: img, img_size: size})
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1095, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("inputs/Placeholder:0", shape=(?, ?, ?, 3), dtype=float32) is not an element of this graph.

在读图时似乎图的尺寸没有读到，视频也有类似问题

**Comment by YangZeyu95** [comment]
run.py 的 line 160？

**Comment by jiahui-wei-perso** [comment]
<img width="701" alt="j1" src="https://user-images.githubusercontent.com/36230049/58462906-1eb4ee80-8133-11e9-9b25-8b37126eaeb0.png">
line 160我没有修改，我只是改了导入模型那部分，下图的部分

<img width="699" alt="j2" src="https://user-images.githubusercontent.com/36230049/58462957-37bd9f80-8133-11e9-8e66-6ecf345c27e8.png">

**Comment by YangZeyu95** [comment]
我不知道你这么改是为什么，原始的代码可以正确运行吗
