### ISSUE TITLE
what is the error of "msb006"

### ISSUE THREAD

**Issue by Tony1868388** [YangZeyu95/unofficial-implement-of-openpose#36]
I　ｂｕｉｌｔ　ｔｈｉｓ　ｐｒｏｇｒａｍ　ｉｎ　ｖｓ　２０１７,ａｎｄ　ｃｕｄａ　９．２　ｉｔ　ｍａｔｃｈ　ｃｕｄｎｎ　,ｂｕｔ　ｔｈｅ　ｐｒｏｊｅｃｔ　ｒｕｎｎｉｎｇ　ｔｈｅ　ｖｓ　２０１７　ｈａｓ　ａ　ｅｒｒｏｒ　ａｂｏｕｔ　＂ｍｓｂ　００６＂，Ｉ　ｄｏ　ｎｏｔ　ｈｏｗ　ｔｏ　ｄｅａｌ　ｗｉｔｈ　ｔｈｉｓ　ｐｒｏｂｌｅｍ　.ａｎｄ　ｎｏｗ　Ｉ set  up the environment in linux and try to build this  throungt linux

**Comment by YangZeyu95** [comment]
Sorry, I have not done this in vs and have no idea what dose msb006 mean. It's no need to use vs to build the project and there might be a multithread problem in Windows. Ubuntu is recommended.

**Comment by Tony1868388** [comment]
> Sorry, I have not done this in vs and have no idea what dose msb006 mean. It's no need to use vs to build the project and there might be a multithread problem in Windows. Ubuntu is recommended.

No thanks I had deal with this problem .And this error is the land network .
