### ISSUE TITLE
Question about pose_dataset.py

### ISSUE THREAD

**Issue by Bartopt** [YangZeyu95/unofficial-implement-of-openpose#4]
I want to use this code in my project. My task is to detect the seven visible vertices of the cube. When I prepared the data set according to the COCO format, I found that the function in pose_dataset.py reported an error. After testing, I found that COCO keypoints dataset has 17 keypoints. but cube only have 7, so I want to know how to modify the pose_dataset.py  so that I can solve it. Thanks a lot!

**Comment by YangZeyu95** [comment]
Can you post the error information?

**Comment by Bartopt** [comment]
Thanks for your code，the error is due to the difference in the number of keypoints, I have fixed it.

**Comment by YangZeyu95** [comment]
I’m trying to make dataset but can’t find a suitable label tool which could provide coco format file. Could you tell me which tool you are using?

**Comment by Bartopt** [comment]
My data set are  cubes in the simulation environment, so I use the python script to automatically mark and write the json file in coco format, I don't use the label tool.I know little about label tool. I think you can use other label tool to complete the annotation and then use the script to rewrite annotations in coco format.

**Comment by YangZeyu95** [comment]
Thanks for your suggestion and I have found a annotation tool might helpful. https://github.com/liruilong940607/AnnoSystem.git
