### ISSUE TITLE
Missing body keypoints in output

### ISSUE THREAD

**Issue by yishengpan-wish** [YangZeyu95/unofficial-implement-of-openpose#47]
当我使用自己的照片去测试的时候，请问为什么会有很多个关键点信息缺失了。
![Screenshot from 2019-08-21 10-42-26](https://user-images.githubusercontent.com/51220871/63398501-6bd9f100-c400-11e9-8238-34cf616cf8ed.png)

**Comment by YangZeyu95** [comment]
换张图

**Comment by yishengpan-wish** [comment]
> 换张图

我试了好几张我自己的照片，都是关键点缺失，是因为这是半身照么

**Comment by YangZeyu95** [comment]
应该是没影响的，视频试一下看看全身行不行
