### ISSUE TITLE
训练代码好像不能使用ＧＰＵ？

### ISSUE THREAD

**Issue by Gzzgz** [YangZeyu95/unofficial-implement-of-openpose#48]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   50C    P8     6W / 120W |    366MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by YangZeyu95** [comment]
如果你正确安装了gpu版的TensorFlow，会自动调用GPU，建议测试一下
