### ISSUE TITLE
训练时候出现以下错误

### ISSUE THREAD

**Issue by Gzzgz** [YangZeyu95/unofficial-implement-of-openpose#49]
[2019-09-02 13:19:42,680] [train] [INFO] echos=0.067636, setp=800, total_loss=328.150238, lr=0.000100
  8%|██▍                             | 899/11828 [16:32:26<200:52:08, 66.17s/it][2019-09-02 15:10:04,099] [train] [INFO] echos=0.076091, setp=900, total_loss=158.620926, lr=0.000100
  8%|██▋                             | 999/11828 [18:23:09<199:12:21, 66.22s/it][2019-09-02 17:00:47,341] [train] [INFO] echos=0.084545, setp=1000, total_loss=467.270477, lr=0.000100
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
/usr/local/lib/python3.6/dist-packages/tensorflow/python/../libtensorflow_framework.so(+0x6ae97b)[0x7f727e64697b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f72a02dc390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f729ff36428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f729ff3802a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d)[0x7f727da9d84d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d6b6)[0x7f727da9b6b6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d701)[0x7f727da9b701]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8d38)[0x7f727dac6d38]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f72a02d26ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f72a000841d]
*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	
	
	gsignal
	abort
	__gnu_cxx::__verbose_terminate_handler()

**Comment by YangZeyu95** [comment]
what's your TensorFlow version? mine is 1.13
