### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by 16534165** [YangZeyu95/unofficial-implement-of-openpose#51]
when i use the pretrained model to test the video,it has occur
error: OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\imgproc\src\resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
how to resolve this problem

**Comment by YangZeyu95** [comment]
没读到图片，检查一下目录
