### ISSUE TITLE
test视频时最后出现resize 错误

### ISSUE THREAD

**Issue by walkm-an** [YangZeyu95/unofficial-implement-of-openpose#53]
Traceback (most recent call last):
  File "run.py", line 109, in <module>
    img = np.array(cv2.resize(image, (654, h)))
cv2.error: OpenCV(3.4.5) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

我用opencv 4 和 3.4.5 都测试过，跑到最后会出现这个错误，导致不能save output的视频。

谢谢

**Comment by YangZeyu95** [comment]
应该是没读到文件

**Comment by lisa676** [comment]
@walkm-an did you solve this problem? I'm also facing this problem, I don't know how to solve it. @YangZeyu95 would you like to help me?

**Comment by walkm-an** [comment]
> @walkm-an did you solve this problem? I'm also facing this problem, I don't know how to solve it. @YangZeyu95 would you like to help me?

So i didn't try to solve it. I only use camera as input. So to avoid this problem. make sure you have the corrent directory of the video.

**Comment by lisa676** [comment]
@walkm-an thanks for your prompt response. Yes I have valid directory to save the video file but still I'm getting same problem.

**Comment by walkm-an** [comment]
> @walkm-an thanks for your prompt response. Yes I have valid directory to save the video file but still I'm getting same problem.

Try to use web camera as input to see if it works, it works for me.

**Comment by lisa676** [comment]
> > @walkm-an thanks for your prompt response. Yes I have valid directory to save the video file but still I'm getting same problem.
> 
> Try to use web camera as input to see if it works, it works for me.

Thanks for your kind suggestions.
