### ISSUE TITLE
Custom points number

### ISSUE THREAD

**Issue by kurzacz** [YangZeyu95/unofficial-implement-of-openpose#54]
Hello,
I'd like to train network with my own list of points (say, 2, or 52). Is there a convenient way to set in the train parameters how many points and joints I want to use?
Let's suppose I still use Coco type of annotations and I take care of defining point names and skeleton by myself.

**Comment by YangZeyu95** [comment]
There is no convenience way to do that, change all the related code is needed. it's tedious but not hard.
