### ISSUE TITLE
在training的时候，整个程序到底哪部分代码在计算groundtruth PAF

### ISSUE THREAD

**Issue by DrZhu-DataScienceForDecisions** [YangZeyu95/unofficial-implement-of-openpose#57]
I looked through the training, but couldn't find the code that actually calculates the groundtruth PAF and heatmap?

enqueuer = DataFlowToQueue(df, [raw_img, hm, paf], queue_size=100)
    q_inp, q_heat, q_vect = enqueuer.dequeue()
进入到DataFlowToQueue，根本找不到程序哪里在计算groundtruth PAF, please help.

**Comment by YangZeyu95** [comment]
在pose_dataset.py里
