### ISSUE TITLE
训练其他数据集

### ISSUE THREAD

**Issue by ZP-Guo** [YangZeyu95/unofficial-implement-of-openpose#60]
你好，非常感谢你的提供的代码，我已经follow你的这些代码很久了。
我的问题是我现在想用这些代码来训练别的数据集，除了train.py里面我根据自己的想法修改了，请问
（1）pose_dataset.py中的CocoPose(RNGDataFlow).__init()__中的文件路径要改，pose_dataset.py还有什么需要修改的地方吗，
（2）pose_augment.py中的开头部分，_network_w, _network_h, _scale这三个变量需要修改吗，而且w，h好理解，就是train.py中的图片默认大小，scale为什么是2呢，
以上就是我的两个问题，我所使用的数据集格式和COCO是一致的，包括annotation的文件格式等，不太一样的地方可能就是图片尺寸明显比COCO的小很多，大约都在150*150左右。你的代码我试过了，效果挺好的，而且还是tensorflow的，明显比caffe的友好。
非常期待你的回信，谢谢。

**Comment by YangZeyu95** [comment]
1）如果你的数据关节与COCO定义一样就不需要改
2）scale应该设置为8，表示下采样8到1/8
150*150的话比较小，代码会先resize到368*368再进行后续训练，不知道会有什么影响

**Comment by ZP-Guo** [comment]
> 1）如果你的数据关节与COCO定义一样就不需要改
> 2）scale应该设置为8，表示下采样8到1/8
> 150_150的话比较小，代码会先resize到368_368再进行后续训练，不知道会有什么影响

好的好的，非常感谢你的回复，我会继续把工作做下去的。

**Comment by ZHU883000** [comment]
> CocoPose

如果和COCO的关节点定义不一样，应当做哪些修改呢
