### ISSUE TITLE
Help: Problem with training

### ISSUE THREAD

**Issue by Elina-ye** [YangZeyu95/unofficial-implement-of-openpose#67]
Thank you for your sharing.
I tried to train the model by myself, however, I met some problems...

1. At the first, the code works well, but the process stopped at 0% for a long time, it shows that :
"0%|                                                                                        | 0/11828 [00:00<?, ?it/s]"

2. Then the following sentences kept repeating many times after that long time waiting:
"2020-10-26 14:37:06.724670: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue."

3. After repeated those sentences many times, the training was continuing. I noticed the checkpoint will be saved every 1000 times, cause "parser.add_argument('--save_checkpoint_frequency', type=int, default=1000)". However, the training was stopped, I had received an error. The information shows that:
" 8%|██████▍                                                                     | 996/11828 [17:42<2:39:05,  1.1  
8%|██████▍                                                                     | 997/11828 [17:43<2:39:09,  1.1  
8%|██████▍                                                                     | 998/11828 [17:44<2:39:01,  1.1 
8%|██████▍                                                                     | 999/11828 [17:45<2:39:02,  1.13it/s]
[2020-10-26 14:53:14,907] [train] [INFO] echos=0.084545, setp=1000, total_loss=495.363190, lr=0.000100

500it [10:20,  1.24s/it]
  8%|██████▍                                                                     | 999/11828 [28:09<5:05:17,  1.69s/it]
2020-10-26 15:03:35.384219: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    train()
  File "train.py", line 174, in train
    df_valid.reset_state()
  File "D:\anaconda3\envs\tf_gpu\lib\site-packages\tensorpack\dataflow\base.py", line 181, in reset_state
    self.ds.reset_state()
  File "D:\anaconda3\envs\tf_gpu\lib\site-packages\tensorpack\dataflow\parallel.py", line 236, in reset_state
    assert not self._reset_done, "reset_state() was called twice! This violates the API of DataFlow!"
AssertionError: reset_state() was called twice! This violates the API of DataFlow!
[2020-10-26 15:03:35,832] [pose_dataset] [ERROR] err type1, placeholders=[<tf.Tensor 'inputs/Placeholder:0' shape=(10, 368, 368, 3) dtype=float32>, <tf.Tensor 'inputs/Placeholder_1:0' shape=(10, 46, 46, 19) dtype=float32>, <tf.Tensor 'inputs/Placeholder_2:0' shape=(10, 46, 46, 38) dtype=float32>]
[2020-10-26 15:03:35,832] [pose_dataset] [INFO] Thread-1 Exited."

It seems like the error was happened because the "df_valid.reset_state()"was called twice in train.py. Thus, I checked my code and I think there is no conflict between the two commands.  I don't know what should I do to solve it? Can someone help me?

**Comment by jnn13008** [comment]
I'm having the same issue, did you ever find a solution?

**Comment by cohogain** [comment]
@YangZeyu95 I am also experiencing the similar issue as above, would you have any feedback on this error? It is linked with parallel.py when using multiprocesses in pose_dataset

**Comment by YangZeyu95** [comment]
I have disabled the validation in training. Please try again.

**Comment by cohogain** [comment]
This solved the problem for me, thank you!
