### ISSUE TITLE
windows10下的训练问题

### ISSUE THREAD

**Issue by cfsfine** [YangZeyu95/unofficial-implement-of-openpose#70]
您好，run.py测试图片和视频都没问题，但是train会报错，'can only start a process object created by current process'，详细信息如图，貌似是multiprocess在windows上的兼容问题，在网络上没有找到解决办法，请求您的帮助。可以的话，您可以上传一下requirements.txt。
![problem](https://user-images.githubusercontent.com/47968887/111691417-41b11500-8869-11eb-97b4-d0a6730b9870.png)

**Comment by YangZeyu95** [comment]
这个确实是Windows的问题，要不用单线程，要不就Ubuntu。
btw，单线程很慢

**Comment by cfsfine** [comment]
> 这个确实是Windows的问题，要不用单线程，要不就Ubuntu。
> btw，单线程很慢
非常感谢！

**Comment by cfsfine** [comment]
非常感谢！

**Comment by CARASO** [comment]
我的服务器的系统是UBUNTU，也有一样的问题。
Linux ten 4.15.0-140-generic #144~16.04.1-Ubuntu SMP Fri Mar 19 21:24:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
