### ISSUE TITLE
一运行train.py过一会电脑就会重启。。

### ISSUE THREAD

**Issue by Ecalpal** [YangZeyu95/unofficial-implement-of-openpose#8]
emmmm电脑配置是i7-4790+1080Ti，系统、代码、数据集都在一块SSD里。
下载了你的ckpt来进行测试时没问题的，但是一运行train.py过一会电脑就会重启。。求解答。。我下载了VGG的权重按要求放好了数据集，别的什么也没改。

不知道是什么原因呃？

**Comment by YangZeyu95** [comment]
兄弟它是喯儿一下就重启了还是慢慢关机再重启

**Comment by Ecalpal** [comment]
是 嗯~ 一声就重启了。

**Comment by Ecalpal** [comment]
我今天在另一台电脑上试了。我列一下两台电脑的配置
会重启的那台：i7-4760+1080ti+600w电源
可以愉快运行的那台：i7-6700+2080ti+750w电源
毛病可能就是电源吧

**Comment by Ecalpal** [comment]
@YangZeyu95 可以把你的配置发出来看看嘛？

**Comment by YangZeyu95** [comment]
i7-7400+titanxp+750w
2600x+titanxp+600w
会不会是散热不好过热保护了

**Comment by Ecalpal** [comment]
刚刚监测了一下CPU温度和显卡温度。感觉在他突然重启前都是正常的。。。明天我换个电源试试。。。

**Comment by Ecalpal** [comment]
确定是电源问题了。GG思密达
