### ISSUE TITLE
请问下，训练1000步以后，程序不动了是怎么回事呢？

### ISSUE THREAD

**Issue by TongYuQing** [YangZeyu95/unofficial-implement-of-openpose#9]

**Comment by YangZeyu95** [comment]
每1000step会有一次测试来保证储存loss最小的checkpoint，第一次测试会预处理并把数据载进内存，耐心等待，后面的测试就不用重新载入会快很多，如果不想测试可以注释掉line173-190，只留下line186

**Comment by TongYuQing** [comment]
> 每1000step会有一次测试来保证储存loss最小的checkpoint，第一次测试会预处理并把数据载进内存，耐心等待，后面的测试就不用重新载入会快很多，如果不想测试可以注释掉line173-190，只留下line186

感谢抽空回答我的问题，谢谢
